### ISSUE TITLE
Research and Propose a safe and economic robot shipping solution from home to World Championship

### ISSUE THREAD

**Issue by ScientificCodingKids** [ScientificCodingKids/VEX_47114A_Cpp#48]
This case costs $220 + tax + shipping, but I don't think it is very easy to carry. The main selling point is that it is legit for carry-on.
https://www.robosource.net/custom-more/robot-cases/347-robosource-robot-case

Please do your research with the following mind:

- safe: don't break the robot; nowadays parts in short supply, we may not find parts even with $$$ at hand;
- economic: don't expect we can get it very cheap, but we don't like overspend;
- what about batteries? Are they allowed to be carry-on or we must ship it as cargo?

**Comment by chloen13** [comment]
https://www.vexforum.com/t/vex-worlds-tips-for-newbie/25311/4
Includes some robot shipping tips

**Comment by jxu08** [comment]
Some more links: 
- https://www.vexforum.com/t/carrying-vex-iq-robot-on-a-plane/2840 (this is for VEX IQ robots)
- https://www.vexforum.com/t/how-do-people-send-their-robots-to-worlds/18682
- https://www.vexforum.com/t/vrc-world-championship-robot-shipping-information/15680
- https://www.vexforum.com/search?q=Robot%20shipping
