### ISSUE TITLE
Take notes on location tracking math

### ISSUE THREAD

**Issue by ScientificCodingKids** [ScientificCodingKids/VEX_47114A_Cpp#51]

**Comment by ScientificCodingKids** [comment]
stay tuned and git pull often -- Chloe and me will push code related to location tracking frequently.

**Comment by jxu08** [comment]
https://docs.google.com/document/d/1DyE_FA2z2u3HZVOLJGvFlAR7UNX5U3RACvFWD20UUlI/edit
