### ISSUE TITLE
Add rubber band to lift and review its effectiveness

### ISSUE THREAD

**Issue by ScientificCodingKids** [ScientificCodingKids/VEX_47114A_Cpp#6]
Do we really get any help?

Note if it works against the robot, that suggests the rubber band is attached incorrectly. At least it should be as equally good as without it.

**Comment by chloen13** [comment]
Using 8 rubber bands, the lift can stand upright at almost maximum height on its own. It can lift 3 balls to max height with motors.
There had to be a lot of tension for this to happen (we doubled the rubber band so that it is shorter).

**Comment by ScientificCodingKids** [comment]
Awesome!
