### ISSUE TITLE
Resolve the stuck drivetrain due to wheel and gear are too close

### ISSUE THREAD

**Issue by ScientificCodingKids** [ScientificCodingKids/VEX_47114A_Cpp#7]
Wheel (esp left) is in touch with gear, so it can barely rotate. 

It is very time consuming to redo the drive train base and even adjust the distance between the two -- there may be no such spacer to do the job.

But we have to fix it otherwise, the robot cannot even rotate even the front wheels can rotate.

**Comment by chloen13** [comment]
After sanding down the gear to make it thinner, the wheel can rotate.
